### ISSUE TITLE
SQL Importer does not support Kerberos

### ISSUE THREAD

**Issue by tuxassault** [mapd/mapd-core#191]
I am trying to import data into MapD with the SQLImporter from a Kerberos Hive2 server. This doesn't appear to work because it cannot find the Kerberos tgt. I have done kinit and i have given the connection string i successfully use in beeline to the importer. 

Does anyone know if Kerberos is supported for SQLImport?

I get the error :

Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at org.apache.hive.service.auth.HttpAuthUtils$HttpKerberosClientAction.run(HttpAuthUtils.java:183)
        at org.apache.hive.service.auth.HttpAuthUtils$HttpKerberosClientAction.run(HttpAuthUtils.java:151)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866)

**Comment by RalphLoen** [comment]
At present, neither MapD Core nor the MapD JDBC client support Kerberos authentication.

**Comment by tuxassault** [comment]
Is there plans to develop this functionality? Much of the data we would want to use GPU databases is locked away in a Kerberized Hadoop instance. Is there a reasonable workaround you can think of?

**Comment by RalphLoen** [comment]
How does your Hive environment invoke SQLImporter?  The error message seems
to indicate that the Kerberos authentication problems are coming from the
source (non-MapD) data node, If may be possible to use Kerberos to
authenticate to the source data node and then use SQLImporter to import the
data into MapD.

**Comment by tuxassault** [comment]
I was using the documentation from MapD on how to use the SQL Importer with the two jdbc drivers added to the classpath. I tried to use the MapD jdbc driver and the HortonWorks Hive2 standalone driver along with a bunch of Hadoop specific jar files

java -Djavax.security.auth.useSubjectCredsOnly=false -cp /usr/mapd/lib/mapd-1.0-SNAPSHOT-jar-with-dependencies.jar:/usr/hdp/current/hive-client/jdbc/hive-jdbc-1.2.1000.2.6.1.0-129-standalone.jar:/usr/hdp/current/hadoop-client/hadoop-common.jar:/usr/hdp/current/hadoop-client/hadoop-auth.jar:/usr/hdp/current/hadoop-client/lib/commons-configuration-1.6.jar:/usr/hdp/current/hadoop-hdfs-client/lib/xercesImpl-2.9.1.jar:/usr/hdp/current/hadoop-hdfs-client/lib/xml-apis-1.3.04.jar com.mapd.utility.SQLImporter

This gives me a different error that definitely feels like Hadoop Hive2 driver stuff, i will see if HortonWorks support can help me sort it out. They may be unwilling as they will probably claim that it is because i am using MapD SQL Importer libraries.

If you want me to keep the issue open and log if i make any progress with them i am okay with doing that. If not then i will close the issue as to not clog up the issues on your github.

Thanks

**Comment by tuxassault** [comment]
I am worried that even if i get Kerberos sorted i will hit a snag because the MapD jar file requires a -su and -sp for the credentials, which i have been passing empty strings (i assume this will bite me eventually)

**Comment by RalphLoen** [comment]
Correction.  Only the source database needs to be JDBC-compliant, not the MapD side.

**Comment by randyzwitch** [comment]
Closing this issue for now, as this issue seems to be more on the Hadoop side of things per Ralph's comment, not a MapD issue per se
