### ISSUE TITLE
how to repair/remove a corrupted table?

### ISSUE THREAD

**Issue by fleapapa** [mapd/mapd-core#94]
While i tried to reproduce [issue #82](https://github.com/mapd/mapd-core/issues/82), the table seemed somehow corrupted. 

Then i tried to drop the table but that always causes mapd_server to abort, so does SELECT query on the table.

What should i do to repair or remove it entirely from file system?

Here is the back trace:

```
E0924 14:17:57.400048 13443 FileMgr.cpp:554] Failed to get chunk 1,2,1,0,
F0924 14:17:57.400260 13443 FileMgr.cpp:555] Chunk does not exist.1,2,1,0,
*** Check failure stack trace: ***
    @     0x7f846d19f5cd  google::LogMessage::Fail()
    @     0x7f846d1a1433  google::LogMessage::SendToLog()
    @     0x7f846d19f15b  google::LogMessage::Flush()
    @     0x7f846d1a1e1e  google::LogMessageFatal::~LogMessageFatal()
    @          0x176dfc6  File_Namespace::FileMgr::getBuffer()
    @          0x176731c  File_Namespace::GlobalFileMgr::getBuffer()
    @          0x1754fea  Data_Namespace::DataMgr::getChunkBuffer()
    @          0x179ec8e  Chunk_NS::Chunk::getChunkBuffer()
    @          0x1795af0  Fragmenter_Namespace::InsertOrderFragmenter::getChunkMetadata()
    @          0x1795133  Fragmenter_Namespace::InsertOrderFragmenter::InsertOrderFragmenter()
    @          0x12c3c6d  Catalog_Namespace::Catalog::instantiateFragmenter()
    @          0x12c3e3d  Catalog_Namespace::Catalog::getMetadataForTable()
    @          0x1251b51  MapDHandler::get_table_details_impl()
    @          0x1251a82  MapDHandler::get_internal_table_details()
    @          0x11c4fc8  MapDProcessor::process_get_internal_table_details()
    @          0x11c1b41  MapDProcessor::dispatchCall()
    @          0x1166dce  apache::thrift::TDispatchProcessor::process()
    @     0x7f846c9195c2  apache::thrift::server::TConnectedClient::run()
    @     0x7f846c8e5a94  apache::thrift::concurrency::ThreadManager::Worker::run()
    @     0x7f846c925833  apache::thrift::concurrency::PthreadThread::threadMain()
    @     0x7f846afac6ba  start_thread
    @     0x7f846ace23dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)
/data/github/mapd-core> 2017-09-24 14:17:57 ERROR MetaConnect:get_table_details:251 - org.apache.thrift.transport.TTransportException
2017-09-24 14:17:57 ERROR CalciteServerHandler:process:108 - Exception occurred: java.lang.RuntimeException: org.apache.thrift.transport.TTransportException
2017-09-24 14:17:57 WARN  TIOStreamTransport:close:112 - Error closing output stream.
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
	at org.apache.thrift.transport.TSocket.close(TSocket.java:235)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by fleapapa** [comment]
Never mind. I removed entire data dir and re-ran bin/initdb to create another one.
